# ------------------------------------------------------------------------------
# Development WordPress and MySQL database containers
# ------------------------------------------------------------------------------

services:

  # ----------------------------------------------------------------------------
  # Create a MySQL container with a pre-configured WordPress database schema
  # ----------------------------------------------------------------------------
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PWD}
    volumes:
      - data:/var/lib/mysql
    ports:
      - '3306:3306'

  # ----------------------------------------------------------------------------
  # Create a WordPress container connected to the 'db' container
  # ----------------------------------------------------------------------------
  web:
    image: wordpress
    ports:
      - '8080:80'
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PWD}
      - WORDPRESS_TABLE_PREFIX=${DB_PREFIX}
    volumes:
      - ${WP_CONTENT}:/var/www/html

  # ----------------------------------------------------------------------------
  # Optional: Create an Adminer container
  # ----------------------------------------------------------------------------
  adminer:
    image: adminer
    ports:
      - '8081:8080'

  # ----------------------------------------------------------------------------
  # Optional: Create a phpMyAdmin container - pre-connected to 'db'
  # ----------------------------------------------------------------------------
  phpmyadmin:
    image: phpmyadmin
    ports:
      - '8082:80'
    environment:
      - PMA_HOST=db
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PWD}

volumes:
  # ----------------------------------------------------------------------------
  # Define a data volume to persist MySQL data across Ups and Downs
  # ----------------------------------------------------------------------------
  data:
